version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: quarkus-postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: observer
      POSTGRES_PASSWORD: theOverlookingEagle
    ports:
      - "5432:5432"
    networks:
      - quarkus-net

  quarkus:
    image: quarkus/observe-jvm
    container_name: quarkus-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/mydb
      QUARKUS_DATASOURCE_USERNAME: observer
      QUARKUS_DATASOURCE_PASSWORD: theOverlookingEagle
      # Optional: if you use custom config loading via env var
      # MYCONFIG_PATH: file:/deployments/config/system-config.yaml
    # Optional: mount your system-config.yaml file (uncomment if needed)
    # volumes:
    #   - ./config/system-config.yaml:/deployments/config/system-config.yaml:ro
    networks:
      - quarkus-net

networks:
  quarkus-net:
    driver: bridge