version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: quarkus-postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: observer
      POSTGRES_PASSWORD: theOverlookingEagle
    ports:
      - "5432:5432"