version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: quarkus-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpw
    ports:
      - "5432:5432"
    volumes:
      # Init scripts
      - ./db-init-scripts:/docker-entrypoint-initdb.d:ro
      # Persistent data
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quarkus-net

  quarkus:
    image: quarkus/observe-jvm
    container_name: quarkus-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/mydb
      QUARKUS_DATASOURCE_USERNAME: observer
      QUARKUS_DATASOURCE_PASSWORD: theOverlookingEagle
      # Optional: if you use custom config loading via env var
      # MYCONFIG_PATH: file:/deployments/config/system-config.yaml
    # Optional: mount your system-config.yaml file (uncomment if needed)
    # volumes:
    #   - ./config/system-config.yaml:/deployments/config/system-config.yaml:ro
    networks:
      - quarkus-net

volumes:
  postgres_data:
    driver: local

networks:
  quarkus-net:
    driver: bridge
