version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: quarkus-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpw
    ports:
      - "5432:5432"
    volumes:
      # Init scripts
      - ./db-init-scripts:/docker-entrypoint-initdb.d:ro
      # Persistent data
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quarkus-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - quarkus-net
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This allows Prometheus to reach your host

  quarkus:
    image: quarkus/observe-jvm
    container_name: quarkus-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/mydb
      QUARKUS_DATASOURCE_USERNAME: observer
      QUARKUS_DATASOURCE_PASSWORD: theOverlookingEagle
      # Optional: if you use custom config loading via env var
      # MYCONFIG_PATH: file:/deployments/config/system-config.yaml
    # Optional: mount your system-config.yaml file (uncomment if needed)
    # volumes:
    #   - ./config/system-config.yaml:/deployments/config/system-config.yaml:ro
    networks:
      - quarkus-net

volumes:
  postgres_data:
    driver: local
  prometheus_data:

networks:
  quarkus-net:
    driver: bridge
