quarkus:
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    log:
      sql: true
    scripts:
      generation:
        create: true
        drop: never
        update: true

  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jdbc:
      url: ${DB_URL}

"%dev":
  quarkus:
    config:
      locations: dotenv