quarkus:
  datasource:
    db-kind: postgresql
    username: observer
    password: theOverlookingEagle
    jdbc:
      url: jdbc:postgresql://localhost:5432/mydb

  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    log:
      sql: true
    scripts:
      generation:
        create: true
        drop: never
        update: true