quarkus:
  log:
    level: INFO
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
    log:
      sql: true

  datasource:
    db-kind: postgresql
    username: observer
    password: theOverlookingEagle
    jdbc:
      url: jdbc:postgresql://localhost:5432/observe_db
    devservices:
      enabled: true
      show-logs: true
  rest-client:
    prometheus-ram-client:
        url: ${PROMETHEUS_BASE_URL}

app:
  prometheus:
    base-url: ${PROMETHEUS_BASE_URL}
