quarkus:
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
    log:
      sql: true

  datasource:
    db-kind: postgresql
    username: observer
    password: theOverlookingEagle
    jdbc:
      url: jdbc:postgresql://localhost:5432/mydb

my-config:
  config-location: ${config-location:file:config/system-config.yml}