name: Quarkus ci

on:
  push:
    branches: [ "**" ]        # Run on any branch
  pull_request:
    branches: [ "**" ]        # For any PR
  workflow_dispatch:          # Allow manual trigger

jobs:
  test:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Initialize PostgreSQL with custom schema
        run: |
          # Wait for PostgreSQL to be ready
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

          # Run the initialization script
          PGPASSWORD=postgres psql -h localhost -U postgres -f db-init-scripts/init.dev.sql

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Quarkus tests
        run: ./gradlew clean build