name: Quarkus ci

on:
  push:
    branches: [ "**" ]        # Run on any branch
  pull_request:
    branches: [ "**" ]        # For any PR
  workflow_dispatch:          # Allow manual trigger

jobs:
  test:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL and initialize database
        run: |
          # Wait for PostgreSQL with timeout
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..30}; do
            if PGPASSWORD=postgres psql -h localhost -U postgres -c '\q' >/dev/null 2>&1; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Attempt $i/30: PostgreSQL not ready, waiting..."
            sleep 2
          done

          # Verify connection works
          PGPASSWORD=postgres psql -h localhost -U postgres -c 'SELECT version();'

          # Run the initialization script
          echo "Running database initialization..."
          PGPASSWORD=postgres psql -h localhost -U postgres -f db-init-scripts/init.dev.sql

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Quarkus tests
        run: ./gradlew clean build