name: Self-Hosted CPU Stress Test

on:
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  stress-test:
    runs-on: self-hosted
    steps:
      - name: Print core count
        run: |
          echo "Detected cores: $(nproc)"

      - name: Install stress
        run: |
          echo "Installing stress..."
          sudo apt-get update
          sudo apt-get install -y stress

      - name: Run CPU stress for 10 seconds
        run: |
          echo "Starting stress test on all cores for 10 seconds..."
          stress --cpu $(nproc) --timeout 10
          echo "Stress test completed."
