name: Self-Hosted Runner Test

on:
  workflow_dispatch: # allows you to trigger it manually from the GitHub UI

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Start test
        run: echo "Testing self-hosted runner..."

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: End test
        run: echo "Test complete. Runner is working."
